import React, { Component } from 'react'
import MyButton from "../MyButton";
import '../css/LoginView.scss';
import GoogleLogin from 'react-google-login';
import SpecialLogin from '../SpecialLogin';

class LoginView extends Component {
    constructor(props) {
        super(props);
    }

    doGoogleLogin = async (token) => {
        console.log("doGoogleLogin START");
        const requestOptions = {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                token: token
            })
        };
        try {
            const response = await fetch('/user/googlelogin', requestOptions);
            if (!response.ok) {
                const jsonResp = await response.json();
                console.log(`doLogin: response NOT OK: ${JSON.stringify(jsonResp)}`);
            } else {
                // Check for errors generated by express-validator.
                const jsonResp = await response.json();
                let reply = jsonResp.reply;
                if (reply.status === "SUCCESS") {
                    console.log("doGoogleLogin: SUCCESS");
                    this.props.onLogin(reply);
                } else {
                    alert(`${reply.errorMsg}`);
                }
            }
        } catch (error) {
            console.log(error);
        }
    }

    handleGoogleResponse = (response) => {
        //console.log(`LoginView: handleGoogleResponse: ${JSON.stringify(response)}`);
        let token = response.tokenId;
        this.doGoogleLogin(token);
    }

    render() {
        return (
            <div className="loginViewDiv">
                <div className="loginWelcomeMsg">
                    <span>Please sign in to continue</span>
                </div>
                <div className="loginGoogleDiv">
                    <span className="loginInstructionText">Sign in with Google account</span>
                    <div className="loginGoogleBtnDiv">
                        <GoogleLogin
                            clientId="143514624122-ie3dtumrn2f28ge6hlntvmj7v45j4k8o.apps.googleusercontent.com"
                            buttonText="Sign In with Google"
                            onSuccess={this.handleGoogleResponse}
                            onFailure={this.handleGoogleResponse}
                            cookiePolicy={'single_host_origin'}
                        />
                    </div>
                </div>
                {process.env.NODE_ENV === 'development' ? <SpecialLogin onLogin={this.props.onLogin}/> : null}
            </div>
        );
    }
}

export default LoginView;
